# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(772, 782)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 891, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("board.png"))
        self.label.setObjectName("label")
        self.b92 = QtWidgets.QPushButton(Dialog)
        self.b92.setGeometry(QtCore.QRect(10, 670, 101, 91))
        self.b92.setText("")
        self.b92.setObjectName("b92")
        self.b93 = QtWidgets.QPushButton(Dialog)
        self.b93.setGeometry(QtCore.QRect(100, 670, 101, 90))
        self.b93.setText("")
        self.b93.setObjectName("b93")
        self.b94 = QtWidgets.QPushButton(Dialog)
        self.b94.setGeometry(QtCore.QRect(200, 670, 101, 91))
        self.b94.setText("")
        self.b94.setObjectName("b94")
        self.b95 = QtWidgets.QPushButton(Dialog)
        self.b95.setGeometry(QtCore.QRect(290, 670, 101, 91))
        self.b95.setText("")
        self.b95.setObjectName("b95")
        self.b96 = QtWidgets.QPushButton(Dialog)
        self.b96.setGeometry(QtCore.QRect(380, 670, 101, 91))
        self.b96.setText("")
        self.b96.setObjectName("b96")
        self.b97 = QtWidgets.QPushButton(Dialog)
        self.b97.setGeometry(QtCore.QRect(470, 670, 101, 91))
        self.b97.setText("")
        self.b97.setObjectName("b97")
        self.b98 = QtWidgets.QPushButton(Dialog)
        self.b98.setGeometry(QtCore.QRect(560, 670, 101, 91))
        self.b98.setText("")
        self.b98.setObjectName("b98")
        self.b99 = QtWidgets.QPushButton(Dialog)
        self.b99.setGeometry(QtCore.QRect(650, 670, 101, 91))
        self.b99.setText("")
        self.b99.setObjectName("b99")
        self.b82 = QtWidgets.QPushButton(Dialog)
        self.b82.setGeometry(QtCore.QRect(10, 580, 101, 91))
        self.b82.setText("")
        self.b82.setObjectName("b82")
        self.b83 = QtWidgets.QPushButton(Dialog)
        self.b83.setGeometry(QtCore.QRect(100, 580, 101, 91))
        self.b83.setText("")
        self.b83.setObjectName("b83")
        self.b84 = QtWidgets.QPushButton(Dialog)
        self.b84.setGeometry(QtCore.QRect(190, 580, 101, 91))
        self.b84.setText("")
        self.b84.setObjectName("b84")
        self.b85 = QtWidgets.QPushButton(Dialog)
        self.b85.setGeometry(QtCore.QRect(290, 580, 101, 91))
        self.b85.setText("")
        self.b85.setObjectName("b85")
        self.b86 = QtWidgets.QPushButton(Dialog)
        self.b86.setGeometry(QtCore.QRect(380, 580, 101, 91))
        self.b86.setText("")
        self.b86.setObjectName("b86")
        self.b87 = QtWidgets.QPushButton(Dialog)
        self.b87.setGeometry(QtCore.QRect(470, 580, 101, 91))
        self.b87.setText("")
        self.b87.setObjectName("b87")
        self.b88 = QtWidgets.QPushButton(Dialog)
        self.b88.setGeometry(QtCore.QRect(560, 580, 101, 91))
        self.b88.setText("")
        self.b88.setObjectName("b88")
        self.b89 = QtWidgets.QPushButton(Dialog)
        self.b89.setGeometry(QtCore.QRect(650, 580, 101, 91))
        self.b89.setText("")
        self.b89.setObjectName("b89")
        self.b32 = QtWidgets.QPushButton(Dialog)
        self.b32.setGeometry(QtCore.QRect(10, 120, 101, 91))
        self.b32.setText("")
        self.b32.setObjectName("b32")
        self.b33 = QtWidgets.QPushButton(Dialog)
        self.b33.setGeometry(QtCore.QRect(100, 120, 101, 91))
        self.b33.setText("")
        self.b33.setObjectName("b33")
        self.b34 = QtWidgets.QPushButton(Dialog)
        self.b34.setGeometry(QtCore.QRect(200, 120, 101, 91))
        self.b34.setText("")
        self.b34.setObjectName("b34")
        self.pion4N = QtWidgets.QPushButton(Dialog)
        self.pion4N.setGeometry(QtCore.QRect(290, 120, 101, 91))
        self.pion4N.setText("")
        self.pion4N.setObjectName("pion4N")
        self.b36 = QtWidgets.QPushButton(Dialog)
        self.b36.setGeometry(QtCore.QRect(380, 120, 101, 91))
        self.b36.setText("")
        self.b36.setObjectName("b36")
        self.b37 = QtWidgets.QPushButton(Dialog)
        self.b37.setGeometry(QtCore.QRect(470, 120, 101, 91))
        self.b37.setText("")
        self.b37.setObjectName("b37")
        self.b38 = QtWidgets.QPushButton(Dialog)
        self.b38.setGeometry(QtCore.QRect(560, 120, 101, 91))
        self.b38.setText("")
        self.b38.setObjectName("b38")
        self.b39 = QtWidgets.QPushButton(Dialog)
        self.b39.setGeometry(QtCore.QRect(650, 120, 101, 91))
        self.b39.setText("")
        self.b39.setObjectName("b39")
        self.b22 = QtWidgets.QPushButton(Dialog)
        self.b22.setGeometry(QtCore.QRect(10, 30, 101, 91))
        self.b22.setText("")
        self.b22.setObjectName("b22")
        self.b23 = QtWidgets.QPushButton(Dialog)
        self.b23.setGeometry(QtCore.QRect(100, 30, 101, 90))
        self.b23.setText("")
        self.b23.setObjectName("b23")
        self.b24 = QtWidgets.QPushButton(Dialog)
        self.b24.setGeometry(QtCore.QRect(200, 30, 101, 91))
        self.b24.setText("")
        self.b24.setObjectName("b24")
        self.reineN = QtWidgets.QPushButton(Dialog)
        self.reineN.setGeometry(QtCore.QRect(290, 30, 101, 91))
        self.reineN.setText("")
        self.reineN.setObjectName("reineN")
        self.b26 = QtWidgets.QPushButton(Dialog)
        self.b26.setGeometry(QtCore.QRect(380, 30, 101, 91))
        self.b26.setText("")
        self.b26.setObjectName("b26")
        self.b27 = QtWidgets.QPushButton(Dialog)
        self.b27.setGeometry(QtCore.QRect(470, 30, 101, 91))
        self.b27.setText("")
        self.b27.setObjectName("b27")
        self.b28 = QtWidgets.QPushButton(Dialog)
        self.b28.setGeometry(QtCore.QRect(560, 30, 101, 91))
        self.b28.setText("")
        self.b28.setObjectName("b28")
        self.b29 = QtWidgets.QPushButton(Dialog)
        self.b29.setGeometry(QtCore.QRect(650, 30, 101, 91))
        self.b29.setText("")
        self.b29.setObjectName("b29")
        self.b35 = QtWidgets.QPushButton(Dialog)
        self.b35.setGeometry(QtCore.QRect(290, 120, 101, 91))
        self.b35.setText("")
        self.b35.setObjectName("b35")
        self.b25 = QtWidgets.QPushButton(Dialog)
        self.b25.setGeometry(QtCore.QRect(290, 30, 101, 91))
        self.b25.setText("")
        self.b25.setObjectName("b25")
        self.b72 = QtWidgets.QPushButton(Dialog)
        self.b72.setGeometry(QtCore.QRect(10, 490, 101, 91))
        self.b72.setText("")
        self.b72.setObjectName("b72")
        self.b62 = QtWidgets.QPushButton(Dialog)
        self.b62.setGeometry(QtCore.QRect(20, 390, 101, 91))
        self.b62.setText("")
        self.b62.setObjectName("b62")
        self.b52 = QtWidgets.QPushButton(Dialog)
        self.b52.setGeometry(QtCore.QRect(10, 300, 101, 91))
        self.b52.setText("")
        self.b52.setObjectName("b52")
        self.b42 = QtWidgets.QPushButton(Dialog)
        self.b42.setGeometry(QtCore.QRect(10, 210, 101, 91))
        self.b42.setText("")
        self.b42.setObjectName("b42")
        self.b43 = QtWidgets.QPushButton(Dialog)
        self.b43.setGeometry(QtCore.QRect(110, 210, 101, 91))
        self.b43.setText("")
        self.b43.setObjectName("b43")
        self.b53 = QtWidgets.QPushButton(Dialog)
        self.b53.setGeometry(QtCore.QRect(110, 300, 101, 91))
        self.b53.setText("")
        self.b53.setObjectName("b53")
        self.b63 = QtWidgets.QPushButton(Dialog)
        self.b63.setGeometry(QtCore.QRect(110, 390, 101, 91))
        self.b63.setText("")
        self.b63.setObjectName("b63")
        self.b73 = QtWidgets.QPushButton(Dialog)
        self.b73.setGeometry(QtCore.QRect(110, 490, 101, 91))
        self.b73.setText("")
        self.b73.setObjectName("b73")
        self.b44 = QtWidgets.QPushButton(Dialog)
        self.b44.setGeometry(QtCore.QRect(200, 210, 101, 91))
        self.b44.setText("")
        self.b44.setObjectName("b44")
        self.b54 = QtWidgets.QPushButton(Dialog)
        self.b54.setGeometry(QtCore.QRect(200, 300, 101, 91))
        self.b54.setText("")
        self.b54.setObjectName("b54")
        self.b64 = QtWidgets.QPushButton(Dialog)
        self.b64.setGeometry(QtCore.QRect(200, 390, 101, 91))
        self.b64.setText("")
        self.b64.setObjectName("b64")
        self.b74 = QtWidgets.QPushButton(Dialog)
        self.b74.setGeometry(QtCore.QRect(200, 490, 101, 91))
        self.b74.setText("")
        self.b74.setObjectName("b74")
        self.b45 = QtWidgets.QPushButton(Dialog)
        self.b45.setGeometry(QtCore.QRect(290, 210, 101, 91))
        self.b45.setText("")
        self.b45.setObjectName("b45")
        self.b55 = QtWidgets.QPushButton(Dialog)
        self.b55.setGeometry(QtCore.QRect(290, 300, 101, 91))
        self.b55.setText("")
        self.b55.setObjectName("b55")
        self.b65 = QtWidgets.QPushButton(Dialog)
        self.b65.setGeometry(QtCore.QRect(290, 390, 101, 91))
        self.b65.setText("")
        self.b65.setObjectName("b65")
        self.b75 = QtWidgets.QPushButton(Dialog)
        self.b75.setGeometry(QtCore.QRect(290, 490, 101, 91))
        self.b75.setText("")
        self.b75.setObjectName("b75")
        self.b46 = QtWidgets.QPushButton(Dialog)
        self.b46.setGeometry(QtCore.QRect(380, 210, 101, 91))
        self.b46.setText("")
        self.b46.setObjectName("b46")
        self.b56 = QtWidgets.QPushButton(Dialog)
        self.b56.setGeometry(QtCore.QRect(380, 300, 101, 91))
        self.b56.setText("")
        self.b56.setObjectName("b56")
        self.b66 = QtWidgets.QPushButton(Dialog)
        self.b66.setGeometry(QtCore.QRect(380, 390, 101, 91))
        self.b66.setText("")
        self.b66.setObjectName("b66")
        self.b76 = QtWidgets.QPushButton(Dialog)
        self.b76.setGeometry(QtCore.QRect(380, 490, 101, 91))
        self.b76.setText("")
        self.b76.setObjectName("b76")
        self.b47 = QtWidgets.QPushButton(Dialog)
        self.b47.setGeometry(QtCore.QRect(470, 210, 101, 91))
        self.b47.setText("")
        self.b47.setObjectName("b47")
        self.b57 = QtWidgets.QPushButton(Dialog)
        self.b57.setGeometry(QtCore.QRect(470, 300, 101, 91))
        self.b57.setText("")
        self.b57.setObjectName("b57")
        self.b67 = QtWidgets.QPushButton(Dialog)
        self.b67.setGeometry(QtCore.QRect(470, 390, 101, 91))
        self.b67.setText("")
        self.b67.setObjectName("b67")
        self.b77 = QtWidgets.QPushButton(Dialog)
        self.b77.setGeometry(QtCore.QRect(470, 490, 101, 91))
        self.b77.setText("")
        self.b77.setObjectName("b77")
        self.b48 = QtWidgets.QPushButton(Dialog)
        self.b48.setGeometry(QtCore.QRect(560, 210, 101, 91))
        self.b48.setText("")
        self.b48.setObjectName("b48")
        self.b58 = QtWidgets.QPushButton(Dialog)
        self.b58.setGeometry(QtCore.QRect(560, 300, 101, 91))
        self.b58.setText("")
        self.b58.setObjectName("b58")
        self.b68 = QtWidgets.QPushButton(Dialog)
        self.b68.setGeometry(QtCore.QRect(560, 390, 101, 91))
        self.b68.setText("")
        self.b68.setObjectName("b68")
        self.b78 = QtWidgets.QPushButton(Dialog)
        self.b78.setGeometry(QtCore.QRect(560, 490, 101, 91))
        self.b78.setText("")
        self.b78.setObjectName("b78")
        self.b49 = QtWidgets.QPushButton(Dialog)
        self.b49.setGeometry(QtCore.QRect(660, 210, 101, 91))
        self.b49.setText("")
        self.b49.setObjectName("b49")
        self.b59 = QtWidgets.QPushButton(Dialog)
        self.b59.setGeometry(QtCore.QRect(660, 300, 101, 91))
        self.b59.setText("")
        self.b59.setObjectName("b59")
        self.b69 = QtWidgets.QPushButton(Dialog)
        self.b69.setGeometry(QtCore.QRect(660, 390, 101, 91))
        self.b69.setText("")
        self.b69.setObjectName("b69")
        self.b79 = QtWidgets.QPushButton(Dialog)
        self.b79.setGeometry(QtCore.QRect(650, 490, 101, 91))
        self.b79.setText("")
        self.b79.setObjectName("b79")

        # On assigne les images aux pièces

        self.b92.setFlat(True)
        self.b92.setStyleSheet('border:none')
        self.b92.setIcon(QtGui.QIcon("tour1B.png"))
        self.b92.setIconSize(QtCore.QSize(60, 60))

        self.b93.setFlat(True)
        self.b93.setStyleSheet('border:none')
        self.b93.setIcon(QtGui.QIcon("cavalier1B.png"))
        self.b93.setIconSize(QtCore.QSize(60, 60))

        self.b94.setFlat(True)
        self.b94.setStyleSheet('border:none')
        self.b94.setIcon(QtGui.QIcon("fou1B.png"))
        self.b94.setIconSize(QtCore.QSize(60, 60))

        self.b95.setFlat(True)
        self.b95.setStyleSheet('border:none')
        self.b95.setIcon(QtGui.QIcon("reineB.png"))
        self.b95.setIconSize(QtCore.QSize(60, 60))

        self.b96.setFlat(True)
        self.b96.setStyleSheet('border:none')
        self.b96.setIcon(QtGui.QIcon("roiB.png"))
        self.b96.setIconSize(QtCore.QSize(60, 60))

        self.b99.setFlat(True)
        self.b99.setStyleSheet('border:none')
        self.b99.setIcon(QtGui.QIcon("tour2B.png"))
        self.b99.setIconSize(QtCore.QSize(60, 60))

        self.b98.setFlat(True)
        self.b98.setStyleSheet('border:none')
        self.b98.setIcon(QtGui.QIcon("cavalier2B.png"))
        self.b98.setIconSize(QtCore.QSize(60, 60))

        self.b97.setFlat(True)
        self.b97.setStyleSheet('border:none')
        self.b97.setIcon(QtGui.QIcon("fou2B.png"))
        self.b97.setIconSize(QtCore.QSize(60, 60))

        self.b82.setFlat(True)
        self.b82.setStyleSheet('border:none')
        self.b82.setIcon(QtGui.QIcon("pion1B.png"))
        self.b82.setIconSize(QtCore.QSize(60, 60))

        self.b83.setFlat(True)
        self.b83.setStyleSheet('border:none')
        self.b83.setIcon(QtGui.QIcon("pion2B.png"))
        self.b83.setIconSize(QtCore.QSize(60, 60))

        self.b84.setFlat(True)
        self.b84.setStyleSheet('border:none')
        self.b84.setIcon(QtGui.QIcon("pion3B.png"))
        self.b84.setIconSize(QtCore.QSize(60, 60))

        self.b85.setFlat(True)
        self.b85.setStyleSheet('border:none')
        self.b85.setIcon(QtGui.QIcon("pion4B.png"))
        self.b85.setIconSize(QtCore.QSize(60, 60))

        self.b86.setFlat(True)
        self.b86.setStyleSheet('border:none')
        self.b86.setIcon(QtGui.QIcon("pion5B.png"))
        self.b86.setIconSize(QtCore.QSize(60, 60))

        self.b87.setFlat(True)
        self.b87.setStyleSheet('border:none')
        self.b87.setIcon(QtGui.QIcon("pion6B.png"))
        self.b87.setIconSize(QtCore.QSize(60, 60))

        self.b88.setFlat(True)
        self.b88.setStyleSheet('border:none')
        self.b88.setIcon(QtGui.QIcon("pion7B.png"))
        self.b88.setIconSize(QtCore.QSize(60, 60))

        self.b89.setFlat(True)
        self.b89.setStyleSheet('border:none')
        self.b89.setIcon(QtGui.QIcon("pion8B.png"))
        self.b89.setIconSize(QtCore.QSize(60, 60))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        # On connecte les boutons à l'action chk (pour "checked")
        # On doit les connecter à une fonction, mais on veut passer en argument
        # le sender
        # Donc on utilise une fonction anonyme (qui renvoie le résultat de
        # chk(pièce)

        self.b92.pressed.connect(lambda: self.chk(self.b92))
        self.b93.pressed.connect(lambda: self.chk(self.b93))
        self.b94.pressed.connect(lambda: self.chk(self.b94))
        self.b95.pressed.connect(lambda: self.chk(self.b95))
        self.b96.pressed.connect(lambda: self.chk(self.b96))
        self.b99.pressed.connect(lambda: self.chk(self.b99))
        self.b98.pressed.connect(lambda: self.chk(self.b98))
        self.b97.pressed.connect(lambda: self.chk(self.b97))
        self.b82.pressed.connect(lambda: self.chk(self.b82))
        self.b83.pressed.connect(lambda: self.chk(self.b83))
        self.b84.pressed.connect(lambda: self.chk(self.b84))
        self.b85.pressed.connect(lambda: self.chk(self.b85))
        self.b86.pressed.connect(lambda: self.chk(self.b86))
        self.b87.pressed.connect(lambda: self.chk(self.b87))
        self.b88.pressed.connect(lambda: self.chk(self.b88))
        self.b89.pressed.connect(lambda: self.chk(self.b89))

    # Fonction d'action lorsqu'une pièce est sélectionnée

    def chk(self, button): # on passe en argument le sender
        global pChecked
        icon = button.icon()
        print(icon.name())
        name = button.objectName()
        if pChecked == "": # Aucune pièce sélectionnée
            print(name + " sélectionné")
            button.setIcon(QtGui.QIcon(name + "sel.png"))
            pChecked = button
        else: # Une pièce est déjà sélectionnée
            if button == pChecked: # On a sélectionné la pièce déjà sélectionnée
                print(name + " dé-sélectionné")
                button.setIcon(QtGui.QIcon(name + ".png"))
                pChecked = ""
            else: # On a sélectionné une autre pièce
                print(pChecked.objectName() + " dé-sélectionné")
                print(name + " sélectionné")
                pChecked.setIcon(QtGui.QIcon(pChecked.objectName() + ".png"))
                pChecked = button
                namePChecked = pChecked.objectName()
                pChecked.setIcon(QtGui.QIcon(namePChecked + "sel.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
