# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(772, 782)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 891, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("board.png"))
        self.label.setObjectName("label")
        self.b92 = QtWidgets.QPushButton(Dialog)
        self.b92.setGeometry(QtCore.QRect(10, 670, 101, 91))
        self.b92.setText("")
        self.b92.setObjectName("b92")
        self.cavalier1B = QtWidgets.QPushButton(Dialog)
        self.cavalier1B.setGeometry(QtCore.QRect(100, 670, 101, 90))
        self.cavalier1B.setText("")
        self.cavalier1B.setObjectName("cavalier1B")
        self.fou1B = QtWidgets.QPushButton(Dialog)
        self.fou1B.setGeometry(QtCore.QRect(200, 670, 101, 91))
        self.fou1B.setText("")
        self.fou1B.setObjectName("fou1B")
        self.reineB = QtWidgets.QPushButton(Dialog)
        self.reineB.setGeometry(QtCore.QRect(290, 670, 101, 91))
        self.reineB.setText("")
        self.reineB.setObjectName("reineB")
        self.roiB = QtWidgets.QPushButton(Dialog)
        self.roiB.setGeometry(QtCore.QRect(380, 670, 101, 91))
        self.roiB.setText("")
        self.roiB.setObjectName("roiB")
        self.fou2B = QtWidgets.QPushButton(Dialog)
        self.fou2B.setGeometry(QtCore.QRect(470, 670, 101, 91))
        self.fou2B.setText("")
        self.fou2B.setObjectName("fou2B")
        self.cavalier2B = QtWidgets.QPushButton(Dialog)
        self.cavalier2B.setGeometry(QtCore.QRect(560, 670, 101, 91))
        self.cavalier2B.setText("")
        self.cavalier2B.setObjectName("cavalier2B")
        self.tour2B = QtWidgets.QPushButton(Dialog)
        self.tour2B.setGeometry(QtCore.QRect(650, 670, 101, 91))
        self.tour2B.setText("")
        self.tour2B.setObjectName("tour2B")
        self.b82 = QtWidgets.QPushButton(Dialog)
        self.b82.setGeometry(QtCore.QRect(10, 580, 101, 91))
        self.b82.setText("")
        self.b82.setObjectName("b82")
        self.pion2B = QtWidgets.QPushButton(Dialog)
        self.pion2B.setGeometry(QtCore.QRect(100, 580, 101, 91))
        self.pion2B.setText("")
        self.pion2B.setObjectName("pion2B")
        self.pion3B = QtWidgets.QPushButton(Dialog)
        self.pion3B.setGeometry(QtCore.QRect(190, 580, 101, 91))
        self.pion3B.setText("")
        self.pion3B.setObjectName("pion3B")
        self.pion4B = QtWidgets.QPushButton(Dialog)
        self.pion4B.setGeometry(QtCore.QRect(290, 580, 101, 91))
        self.pion4B.setText("")
        self.pion4B.setObjectName("pion4B")
        self.pion5B = QtWidgets.QPushButton(Dialog)
        self.pion5B.setGeometry(QtCore.QRect(380, 580, 101, 91))
        self.pion5B.setText("")
        self.pion5B.setObjectName("pion5B")
        self.pion6B = QtWidgets.QPushButton(Dialog)
        self.pion6B.setGeometry(QtCore.QRect(470, 580, 101, 91))
        self.pion6B.setText("")
        self.pion6B.setObjectName("pion6B")
        self.pion7B = QtWidgets.QPushButton(Dialog)
        self.pion7B.setGeometry(QtCore.QRect(560, 580, 101, 91))
        self.pion7B.setText("")
        self.pion7B.setObjectName("pion7B")
        self.pion8B = QtWidgets.QPushButton(Dialog)
        self.pion8B.setGeometry(QtCore.QRect(650, 580, 101, 91))
        self.pion8B.setText("")
        self.pion8B.setObjectName("pion8B")
        self.pion1N = QtWidgets.QPushButton(Dialog)
        self.pion1N.setGeometry(QtCore.QRect(10, 120, 101, 91))
        self.pion1N.setText("")
        self.pion1N.setObjectName("pion1N")
        self.pion2N = QtWidgets.QPushButton(Dialog)
        self.pion2N.setGeometry(QtCore.QRect(100, 120, 101, 91))
        self.pion2N.setText("")
        self.pion2N.setObjectName("pion2N")
        self.pion3N = QtWidgets.QPushButton(Dialog)
        self.pion3N.setGeometry(QtCore.QRect(200, 120, 101, 91))
        self.pion3N.setText("")
        self.pion3N.setObjectName("pion3N")
        self.pion4N = QtWidgets.QPushButton(Dialog)
        self.pion4N.setGeometry(QtCore.QRect(290, 120, 101, 91))
        self.pion4N.setText("")
        self.pion4N.setObjectName("pion4N")
        self.pion5N = QtWidgets.QPushButton(Dialog)
        self.pion5N.setGeometry(QtCore.QRect(380, 120, 101, 91))
        self.pion5N.setText("")
        self.pion5N.setObjectName("pion5N")
        self.pion6N = QtWidgets.QPushButton(Dialog)
        self.pion6N.setGeometry(QtCore.QRect(470, 120, 101, 91))
        self.pion6N.setText("")
        self.pion6N.setObjectName("pion6N")
        self.pion7N = QtWidgets.QPushButton(Dialog)
        self.pion7N.setGeometry(QtCore.QRect(560, 120, 101, 91))
        self.pion7N.setText("")
        self.pion7N.setObjectName("pion7N")
        self.pion8N = QtWidgets.QPushButton(Dialog)
        self.pion8N.setGeometry(QtCore.QRect(650, 120, 101, 91))
        self.pion8N.setText("")
        self.pion8N.setObjectName("pion8N")
        self.tour1N = QtWidgets.QPushButton(Dialog)
        self.tour1N.setGeometry(QtCore.QRect(10, 30, 101, 91))
        self.tour1N.setText("")
        self.tour1N.setObjectName("tour1N")
        self.cavalier1N = QtWidgets.QPushButton(Dialog)
        self.cavalier1N.setGeometry(QtCore.QRect(100, 30, 101, 90))
        self.cavalier1N.setText("")
        self.cavalier1N.setObjectName("cavalier1N")
        self.fou1N = QtWidgets.QPushButton(Dialog)
        self.fou1N.setGeometry(QtCore.QRect(200, 30, 101, 91))
        self.fou1N.setText("")
        self.fou1N.setObjectName("fou1N")
        self.reineN = QtWidgets.QPushButton(Dialog)
        self.reineN.setGeometry(QtCore.QRect(290, 30, 101, 91))
        self.reineN.setText("")
        self.reineN.setObjectName("reineN")
        self.roiN = QtWidgets.QPushButton(Dialog)
        self.roiN.setGeometry(QtCore.QRect(380, 30, 101, 91))
        self.roiN.setText("")
        self.roiN.setObjectName("roiN")
        self.fou2N = QtWidgets.QPushButton(Dialog)
        self.fou2N.setGeometry(QtCore.QRect(470, 30, 101, 91))
        self.fou2N.setText("")
        self.fou2N.setObjectName("fou2N")
        self.cavalier2N = QtWidgets.QPushButton(Dialog)
        self.cavalier2N.setGeometry(QtCore.QRect(560, 30, 101, 91))
        self.cavalier2N.setText("")
        self.cavalier2N.setObjectName("cavalier2N")
        self.tour2N = QtWidgets.QPushButton(Dialog)
        self.tour2N.setGeometry(QtCore.QRect(650, 30, 101, 91))
        self.tour2N.setText("")
        self.tour2N.setObjectName("tour2N")
        self.v35 = QtWidgets.QPushButton(Dialog)
        self.v35.setGeometry(QtCore.QRect(290, 120, 101, 91))
        self.v35.setText("")
        self.v35.setObjectName("v35")
        self.v25 = QtWidgets.QPushButton(Dialog)
        self.v25.setGeometry(QtCore.QRect(290, 30, 101, 91))
        self.v25.setText("")
        self.v25.setObjectName("v25")
        self.vide_1 = QtWidgets.QPushButton(Dialog)
        self.vide_1.setGeometry(QtCore.QRect(10, 490, 101, 91))
        self.vide_1.setText("")
        self.vide_1.setObjectName("vide_1")
        self.vide_2 = QtWidgets.QPushButton(Dialog)
        self.vide_2.setGeometry(QtCore.QRect(100, 490, 101, 91))
        self.vide_2.setText("")
        self.vide_2.setObjectName("vide_2")
        self.vide_3 = QtWidgets.QPushButton(Dialog)
        self.vide_3.setGeometry(QtCore.QRect(200, 490, 101, 91))
        self.vide_3.setText("")
        self.vide_3.setObjectName("vide_3")
        self.vide_4 = QtWidgets.QPushButton(Dialog)
        self.vide_4.setGeometry(QtCore.QRect(290, 490, 101, 91))
        self.vide_4.setText("")
        self.vide_4.setObjectName("vide_4")
        self.vide_5 = QtWidgets.QPushButton(Dialog)
        self.vide_5.setGeometry(QtCore.QRect(380, 490, 101, 91))
        self.vide_5.setText("")
        self.vide_5.setObjectName("vide_5")
        self.vide_6 = QtWidgets.QPushButton(Dialog)
        self.vide_6.setGeometry(QtCore.QRect(470, 490, 101, 91))
        self.vide_6.setText("")
        self.vide_6.setObjectName("vide_6")
        self.vide_7 = QtWidgets.QPushButton(Dialog)
        self.vide_7.setGeometry(QtCore.QRect(560, 490, 101, 91))
        self.vide_7.setText("")
        self.vide_7.setObjectName("vide_7")
        self.vide_8 = QtWidgets.QPushButton(Dialog)
        self.vide_8.setGeometry(QtCore.QRect(650, 490, 101, 91))
        self.vide_8.setText("")
        self.vide_8.setObjectName("vide_8")
        self.vide_9 = QtWidgets.QPushButton(Dialog)
        self.vide_9.setGeometry(QtCore.QRect(10, 390, 101, 91))
        self.vide_9.setText("")
        self.vide_9.setObjectName("vide_9")
        self.vide_10 = QtWidgets.QPushButton(Dialog)
        self.vide_10.setGeometry(QtCore.QRect(100, 390, 101, 91))
        self.vide_10.setText("")
        self.vide_10.setObjectName("vide_10")
        self.vide_11 = QtWidgets.QPushButton(Dialog)
        self.vide_11.setGeometry(QtCore.QRect(200, 390, 101, 91))
        self.vide_11.setText("")
        self.vide_11.setObjectName("vide_11")
        self.vide_12 = QtWidgets.QPushButton(Dialog)
        self.vide_12.setGeometry(QtCore.QRect(290, 390, 101, 91))
        self.vide_12.setText("")
        self.vide_12.setObjectName("vide_12")
        self.vide_13 = QtWidgets.QPushButton(Dialog)
        self.vide_13.setGeometry(QtCore.QRect(380, 390, 101, 91))
        self.vide_13.setText("")
        self.vide_13.setObjectName("vide_13")
        self.vide_14 = QtWidgets.QPushButton(Dialog)
        self.vide_14.setGeometry(QtCore.QRect(470, 390, 101, 91))
        self.vide_14.setText("")
        self.vide_14.setObjectName("vide_14")
        self.vide_15 = QtWidgets.QPushButton(Dialog)
        self.vide_15.setGeometry(QtCore.QRect(560, 390, 101, 91))
        self.vide_15.setText("")
        self.vide_15.setObjectName("vide_15")
        self.vide_16 = QtWidgets.QPushButton(Dialog)
        self.vide_16.setGeometry(QtCore.QRect(650, 390, 101, 91))
        self.vide_16.setText("")
        self.vide_16.setObjectName("vide_16")
        self.vide_17 = QtWidgets.QPushButton(Dialog)
        self.vide_17.setGeometry(QtCore.QRect(10, 300, 101, 91))
        self.vide_17.setText("")
        self.vide_17.setObjectName("vide_17")
        self.vide_18 = QtWidgets.QPushButton(Dialog)
        self.vide_18.setGeometry(QtCore.QRect(100, 300, 101, 91))
        self.vide_18.setText("")
        self.vide_18.setObjectName("vide_18")
        self.vide_19 = QtWidgets.QPushButton(Dialog)
        self.vide_19.setGeometry(QtCore.QRect(200, 300, 101, 91))
        self.vide_19.setText("")
        self.vide_19.setObjectName("vide_19")
        self.vide_20 = QtWidgets.QPushButton(Dialog)
        self.vide_20.setGeometry(QtCore.QRect(290, 300, 101, 91))
        self.vide_20.setText("")
        self.vide_20.setObjectName("vide_20")
        self.vide_21 = QtWidgets.QPushButton(Dialog)
        self.vide_21.setGeometry(QtCore.QRect(380, 300, 101, 91))
        self.vide_21.setText("")
        self.vide_21.setObjectName("vide_21")
        self.vide_22 = QtWidgets.QPushButton(Dialog)
        self.vide_22.setGeometry(QtCore.QRect(470, 300, 101, 91))
        self.vide_22.setText("")
        self.vide_22.setObjectName("vide_22")
        self.vide_23 = QtWidgets.QPushButton(Dialog)
        self.vide_23.setGeometry(QtCore.QRect(560, 300, 101, 91))
        self.vide_23.setText("")
        self.vide_23.setObjectName("vide_23")
        self.vide_24 = QtWidgets.QPushButton(Dialog)
        self.vide_24.setGeometry(QtCore.QRect(650, 300, 101, 91))
        self.vide_24.setText("")
        self.vide_24.setObjectName("vide_24")
        self.vide_25 = QtWidgets.QPushButton(Dialog)
        self.vide_25.setGeometry(QtCore.QRect(10, 210, 101, 91))
        self.vide_25.setText("")
        self.vide_25.setObjectName("vide_25")
        self.vide_26 = QtWidgets.QPushButton(Dialog)
        self.vide_26.setGeometry(QtCore.QRect(110, 210, 101, 91))
        self.vide_26.setText("")
        self.vide_26.setObjectName("vide_26")
        self.vide_27 = QtWidgets.QPushButton(Dialog)
        self.vide_27.setGeometry(QtCore.QRect(200, 210, 101, 91))
        self.vide_27.setText("")
        self.vide_27.setObjectName("vide_27")
        self.vide_28 = QtWidgets.QPushButton(Dialog)
        self.vide_28.setGeometry(QtCore.QRect(290, 210, 101, 91))
        self.vide_28.setText("")
        self.vide_28.setObjectName("vide_28")
        self.vide_29 = QtWidgets.QPushButton(Dialog)
        self.vide_29.setGeometry(QtCore.QRect(380, 210, 101, 91))
        self.vide_29.setText("")
        self.vide_29.setObjectName("vide_29")
        self.vide_30 = QtWidgets.QPushButton(Dialog)
        self.vide_30.setGeometry(QtCore.QRect(470, 210, 101, 91))
        self.vide_30.setText("")
        self.vide_30.setObjectName("vide_30")
        self.vide_31 = QtWidgets.QPushButton(Dialog)
        self.vide_31.setGeometry(QtCore.QRect(560, 210, 101, 91))
        self.vide_31.setText("")
        self.vide_31.setObjectName("vide_31")
        self.vide_32 = QtWidgets.QPushButton(Dialog)
        self.vide_32.setGeometry(QtCore.QRect(660, 210, 101, 91))
        self.vide_32.setText("")
        self.vide_32.setObjectName("vide_32")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

